version: '2.0'
services:

    php-cli:
        container_name: symfony.php-cli
        image: armdpro/php:7.2-cli
        command: ["./bin/console", "server:run", "0.0.0.0:80"]
        ports:
            - "8082:80"
        volumes:
            - ./:/var/www
        links:
            - mysql:db
        depends_on:
            - composer
            - mysql

    composer:
        container_name: symfony.composer
        image: composer:latest
        volumes:
            - ./:/app
        command: composer install

    phpmyadmin:
        container_name: symfony.phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8085:80"
        links:
            - mysql:db
        depends_on:
            - mysql

    mysql:
        container_name: symfony.mysql
        image: mysql:5.7
        ports:
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=12345
            - MYSQL_PASSWORD=12345
            - MYSQL_DATABASE=users
            - MYSQL_USER=users

    node:
        container_name: symfony.node
        image: "node:8"
        environment:
            - NODE_ENV=dev
        volumes:
            - ./:/var/www
        command: "npm install"