version: '2.0'
services:
    mysql:
        container_name: symfony.mysql
        image: mysql:5.7
        ports:
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=12345
            - MYSQL_PASSWORD=12345
            - MYSQL_DATABASE=users
            - MYSQL_USER=users

    symfony:
        container_name: symfony
        build: .
        ports:
            - "8082:80"
        volumes:
            - ./:/var/www/user-registration
        links:
            - mysql

    phpmyadmin:
        container_name: symfony.phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8085:80"
        links:
            - mysql:db